services:
  # A Docker web service
  - type: web
    name: gokapi
    env: docker
    numInstances: 1
    healthCheckPath: /
    envVars:
    - key: PORT
      value: 53842
    disk:
      name: data
      mountPath: /app/data;/app/config
      sizeGB: 5 # optiona
